services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./data:/data  # Mount the data folder to persist the SQLite database
    environment:
      - DATABASE_URL=sqlite:///./data/test.db  # This tells SQLAlchemy where to store the database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app  # Mount the frontend source code
      - /app/node_modules  # Ensure node_modules is only managed by the container
    depends_on:
      - backend

volumes:
  data: # This is where the SQLite database file will be stored
