services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ./data:/data  # Mount the data folder to persist the SQLite database
    environment:
      - DATABASE_URL=sqlite:///./data/test.db  # This tells SQLAlchemy where to store the database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  data: # This is where the SQLite database file will be stored
